//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolForDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolForDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1610207@dlu.edu.vn.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Quốc Thắng.
        /// </summary>
        internal static string HoTen {
            get {
                return ResourceManager.GetString("HoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ Thông tin.
        /// </summary>
        internal static string Khoa {
            get {
                return ResourceManager.GetString("Khoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTK40.
        /// </summary>
        internal static string Lop {
            get {
                return ResourceManager.GetString("Lop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1610207.
        /// </summary>
        internal static string MSSV {
            get {
                return ResourceManager.GetString("MSSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0987610260.
        /// </summary>
        internal static string SDT {
            get {
                return ResourceManager.GetString("SDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại học Đà Lạt.
        /// </summary>
        internal static string Trường {
            get {
                return ResourceManager.GetString("Trường", resourceCulture);
            }
        }
    }
}
